:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2013.4
:: Copyright (C) 2013 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7k325tffg676-3 ../xilinx_com_hls_nfa_accept_samples_generic_hw_1_0.zip
