// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nfa_accept_sample (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        nfa_initials_buckets_req_din,
        nfa_initials_buckets_req_full_n,
        nfa_initials_buckets_req_write,
        nfa_initials_buckets_rsp_empty_n,
        nfa_initials_buckets_rsp_read,
        nfa_initials_buckets_address,
        nfa_initials_buckets_datain,
        nfa_initials_buckets_dataout,
        nfa_initials_buckets_size,
        nfa_finals_buckets_req_din,
        nfa_finals_buckets_req_full_n,
        nfa_finals_buckets_req_write,
        nfa_finals_buckets_rsp_empty_n,
        nfa_finals_buckets_rsp_read,
        nfa_finals_buckets_address,
        nfa_finals_buckets_datain,
        nfa_finals_buckets_dataout,
        nfa_finals_buckets_size,
        nfa_forward_buckets_req_din,
        nfa_forward_buckets_req_full_n,
        nfa_forward_buckets_req_write,
        nfa_forward_buckets_rsp_empty_n,
        nfa_forward_buckets_rsp_read,
        nfa_forward_buckets_address,
        nfa_forward_buckets_datain,
        nfa_forward_buckets_dataout,
        nfa_forward_buckets_size,
        nfa_symbols,
        sample_req_din,
        sample_req_full_n,
        sample_req_write,
        sample_rsp_empty_n,
        sample_rsp_read,
        sample_address,
        sample_datain,
        sample_dataout,
        sample_size,
        tmp_14,
        length_r,
        ap_return
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   nfa_initials_buckets_req_din;
input   nfa_initials_buckets_req_full_n;
output   nfa_initials_buckets_req_write;
input   nfa_initials_buckets_rsp_empty_n;
output   nfa_initials_buckets_rsp_read;
output  [31:0] nfa_initials_buckets_address;
input  [31:0] nfa_initials_buckets_datain;
output  [31:0] nfa_initials_buckets_dataout;
output  [31:0] nfa_initials_buckets_size;
output   nfa_finals_buckets_req_din;
input   nfa_finals_buckets_req_full_n;
output   nfa_finals_buckets_req_write;
input   nfa_finals_buckets_rsp_empty_n;
output   nfa_finals_buckets_rsp_read;
output  [31:0] nfa_finals_buckets_address;
input  [31:0] nfa_finals_buckets_datain;
output  [31:0] nfa_finals_buckets_dataout;
output  [31:0] nfa_finals_buckets_size;
output   nfa_forward_buckets_req_din;
input   nfa_forward_buckets_req_full_n;
output   nfa_forward_buckets_req_write;
input   nfa_forward_buckets_rsp_empty_n;
output   nfa_forward_buckets_rsp_read;
output  [31:0] nfa_forward_buckets_address;
input  [31:0] nfa_forward_buckets_datain;
output  [31:0] nfa_forward_buckets_dataout;
output  [31:0] nfa_forward_buckets_size;
input  [7:0] nfa_symbols;
output   sample_req_din;
input   sample_req_full_n;
output   sample_req_write;
input   sample_rsp_empty_n;
output   sample_rsp_read;
output  [31:0] sample_address;
input  [7:0] sample_datain;
output  [7:0] sample_dataout;
output  [31:0] sample_size;
input  [31:0] tmp_14;
input  [15:0] length_r;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg nfa_forward_buckets_req_write;
reg nfa_forward_buckets_rsp_read;
reg[31:0] nfa_forward_buckets_address;
reg sample_req_write;
reg sample_rsp_read;
reg[0:0] ap_return;
reg   [6:0] ap_CS_fsm = 7'b0000000;
reg   [31:0] reg_378;
reg   [31:0] current_buckets_0_reg_585;
reg   [31:0] current_buckets_1_reg_590;
wire   [63:0] tmp_14_cast_fu_390_p1;
reg   [63:0] tmp_14_cast_reg_600;
wire   [0:0] tmp_s_fu_405_p2;
reg   [0:0] tmp_s_reg_605;
wire   [15:0] grp_fu_410_p2;
reg   [15:0] i_1_reg_609;
reg   [31:0] sample_addr_1_reg_614;
wire   [0:0] tmp_19_i_fu_428_p2;
reg   [0:0] tmp_19_i_reg_620;
wire   [63:0] grp_fu_422_p2;
reg   [63:0] p_rec_reg_624;
reg   [7:0] sym_reg_629;
wire   [0:0] tmp_19_1_i_fu_434_p2;
reg   [0:0] tmp_19_1_i_reg_634;
wire   [4:0] grp_p_bsf32_hw_fu_372_ap_return;
reg   [4:0] r_bit_reg_638;
wire   [1:0] agg_result_bucket_index_0_lcssa4_i_cast_cast_fu_440_p1;
wire   [7:0] j_bucket_index1_ph_cast_fu_444_p1;
wire   [7:0] j_bit1_ph_cast_fu_448_p1;
wire   [13:0] tmp_7_i_cast_fu_452_p1;
reg   [13:0] tmp_7_i_cast_reg_658;
wire   [0:0] j_end_phi_fu_316_p4;
wire   [5:0] grp_fu_471_p2;
reg   [5:0] state_reg_673;
wire   [13:0] grp_fu_484_p2;
reg   [13:0] tmp_6_i_reg_688;
reg   [7:0] j_bit_reg_693;
reg   [7:0] j_bucket_index_reg_698;
reg   [31:0] j_bucket_reg_703;
reg   [0:0] p_s_reg_708;
wire   [13:0] grp_fu_490_p2;
reg   [13:0] tmp_8_i_reg_713;
wire   [31:0] next_buckets_0_1_fu_546_p2;
reg   [31:0] next_buckets_0_1_reg_731;
wire   [31:0] next_buckets_1_1_fu_552_p2;
reg   [31:0] tmp_buckets_0_reg_741;
reg   [31:0] tmp_buckets_1_reg_746;
wire   [31:0] current_buckets_0_1_fu_566_p2;
reg   [31:0] current_buckets_0_1_reg_751;
wire   [31:0] current_buckets_1_1_fu_571_p2;
reg   [31:0] current_buckets_1_1_reg_756;
wire   [31:0] tmp_1_fu_576_p2;
reg   [31:0] tmp_1_reg_761;
wire   [0:0] tmp_2_fu_580_p2;
reg   [0:0] tmp_2_reg_766;
wire   [31:0] grp_bitset_next_fu_348_p_read;
wire   [7:0] grp_bitset_next_fu_348_r_bit;
wire   [7:0] grp_bitset_next_fu_348_r_bucket_index;
wire   [31:0] grp_bitset_next_fu_348_r_bucket;
wire   [7:0] grp_bitset_next_fu_348_ap_return_0;
wire   [7:0] grp_bitset_next_fu_348_ap_return_1;
wire   [31:0] grp_bitset_next_fu_348_ap_return_2;
wire   [0:0] grp_bitset_next_fu_348_ap_return_3;
reg    grp_bitset_next_fu_348_ap_ce;
reg    grp_nfa_get_initials_fu_360_ap_start;
wire    grp_nfa_get_initials_fu_360_ap_done;
wire    grp_nfa_get_initials_fu_360_ap_idle;
wire    grp_nfa_get_initials_fu_360_ap_ready;
wire    grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_din;
wire    grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_full_n;
wire    grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_write;
wire    grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_empty_n;
wire    grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_read;
wire   [31:0] grp_nfa_get_initials_fu_360_nfa_initials_buckets_address;
wire   [31:0] grp_nfa_get_initials_fu_360_nfa_initials_buckets_datain;
wire   [31:0] grp_nfa_get_initials_fu_360_nfa_initials_buckets_dataout;
wire   [31:0] grp_nfa_get_initials_fu_360_nfa_initials_buckets_size;
wire    grp_nfa_get_initials_fu_360_ap_ce;
wire   [31:0] grp_nfa_get_initials_fu_360_ap_return_0;
wire   [31:0] grp_nfa_get_initials_fu_360_ap_return_1;
wire    grp_nfa_get_finals_fu_366_ap_start;
wire    grp_nfa_get_finals_fu_366_ap_done;
wire    grp_nfa_get_finals_fu_366_ap_idle;
wire    grp_nfa_get_finals_fu_366_ap_ready;
wire    grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_din;
wire    grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_full_n;
wire    grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_write;
wire    grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_empty_n;
wire    grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_read;
wire   [31:0] grp_nfa_get_finals_fu_366_nfa_finals_buckets_address;
wire   [31:0] grp_nfa_get_finals_fu_366_nfa_finals_buckets_datain;
wire   [31:0] grp_nfa_get_finals_fu_366_nfa_finals_buckets_dataout;
wire   [31:0] grp_nfa_get_finals_fu_366_nfa_finals_buckets_size;
wire    grp_nfa_get_finals_fu_366_ap_ce;
wire   [31:0] grp_nfa_get_finals_fu_366_ap_return_0;
wire   [31:0] grp_nfa_get_finals_fu_366_ap_return_1;
wire   [31:0] grp_p_bsf32_hw_fu_372_bus_r;
reg    grp_p_bsf32_hw_fu_372_ap_ce;
reg   [15:0] i_reg_138;
wire   [0:0] any_phi_fu_328_p4;
reg   [63:0] p_01_rec_reg_150;
reg   [31:0] next_buckets_1_reg_162;
reg   [31:0] next_buckets_0_reg_172;
reg   [31:0] bus_assign_reg_182;
reg   [0:0] agg_result_bucket_index_0_lcssa4_i_reg_194;
reg   [31:0] j_bucket1_ph_reg_207;
reg   [1:0] j_bucket_index1_ph_reg_220;
reg   [4:0] j_bit1_ph_reg_231;
reg   [0:0] j_end_ph_reg_242;
reg   [31:0] tmp_buckets_1_3_reg_256;
reg   [31:0] tmp_buckets_0_3_reg_269;
reg   [31:0] j_bucket1_reg_282;
reg   [7:0] j_bucket_index1_reg_293;
reg   [7:0] j_bit1_reg_303;
reg   [0:0] j_end_reg_313;
reg   [0:0] any_reg_323;
reg   [0:0] p_0_reg_336;
reg   [6:0] ap_NS_fsm;
reg    grp_nfa_get_finals_fu_366_ap_start_ap_start_reg = 1'b0;
wire   [63:0] grp_fu_400_p2;
wire   [63:0] tmp_4_i_cast_fu_517_p1;
wire   [63:0] tmp_9_i_cast_fu_535_p1;
wire   [63:0] grp_fu_400_p0;
wire   [63:0] grp_fu_400_p1;
wire   [15:0] grp_fu_410_p0;
wire   [15:0] grp_fu_410_p1;
wire   [63:0] grp_fu_422_p0;
wire   [63:0] grp_fu_422_p1;
wire   [0:0] tmp_31_fu_455_p1;
wire   [5:0] grp_fu_471_p0;
wire   [5:0] grp_fu_471_p1;
wire   [7:0] grp_fu_484_p0;
wire   [5:0] grp_fu_484_p1;
wire   [13:0] grp_fu_490_p0;
wire   [13:0] grp_fu_490_p1;
wire   [14:0] tmp_4_i_fu_510_p3;
wire   [14:0] tmp_9_i_fu_528_p3;
wire    grp_fu_400_ce;
wire    grp_fu_410_ce;
reg    grp_fu_422_ce;
wire    grp_fu_471_ce;
wire    grp_fu_484_ce;
wire    grp_fu_490_ce;
reg   [0:0] ap_return_preg = 1'b0;
wire   [13:0] grp_fu_484_p00;
wire   [13:0] grp_fu_484_p10;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b0000000;
parameter    ap_ST_st2_fsm_1 = 7'b1;
parameter    ap_ST_st3_fsm_2 = 7'b10;
parameter    ap_ST_st4_fsm_3 = 7'b11;
parameter    ap_ST_st5_fsm_4 = 7'b100;
parameter    ap_ST_st6_fsm_5 = 7'b101;
parameter    ap_ST_st7_fsm_6 = 7'b110;
parameter    ap_ST_st8_fsm_7 = 7'b111;
parameter    ap_ST_st9_fsm_8 = 7'b1000;
parameter    ap_ST_st10_fsm_9 = 7'b1001;
parameter    ap_ST_st11_fsm_10 = 7'b1010;
parameter    ap_ST_st12_fsm_11 = 7'b1011;
parameter    ap_ST_st13_fsm_12 = 7'b1100;
parameter    ap_ST_st14_fsm_13 = 7'b1101;
parameter    ap_ST_st15_fsm_14 = 7'b1110;
parameter    ap_ST_st16_fsm_15 = 7'b1111;
parameter    ap_ST_st17_fsm_16 = 7'b10000;
parameter    ap_ST_st18_fsm_17 = 7'b10001;
parameter    ap_ST_st19_fsm_18 = 7'b10010;
parameter    ap_ST_st20_fsm_19 = 7'b10011;
parameter    ap_ST_st21_fsm_20 = 7'b10100;
parameter    ap_ST_st22_fsm_21 = 7'b10101;
parameter    ap_ST_st23_fsm_22 = 7'b10110;
parameter    ap_ST_st24_fsm_23 = 7'b10111;
parameter    ap_ST_st25_fsm_24 = 7'b11000;
parameter    ap_ST_st26_fsm_25 = 7'b11001;
parameter    ap_ST_st27_fsm_26 = 7'b11010;
parameter    ap_ST_st28_fsm_27 = 7'b11011;
parameter    ap_ST_st29_fsm_28 = 7'b11100;
parameter    ap_ST_st30_fsm_29 = 7'b11101;
parameter    ap_ST_st31_fsm_30 = 7'b11110;
parameter    ap_ST_st32_fsm_31 = 7'b11111;
parameter    ap_ST_st33_fsm_32 = 7'b100000;
parameter    ap_ST_st34_fsm_33 = 7'b100001;
parameter    ap_ST_st35_fsm_34 = 7'b100010;
parameter    ap_ST_st36_fsm_35 = 7'b100011;
parameter    ap_ST_st37_fsm_36 = 7'b100100;
parameter    ap_ST_st38_fsm_37 = 7'b100101;
parameter    ap_ST_st39_fsm_38 = 7'b100110;
parameter    ap_ST_st40_fsm_39 = 7'b100111;
parameter    ap_ST_st41_fsm_40 = 7'b101000;
parameter    ap_ST_st42_fsm_41 = 7'b101001;
parameter    ap_ST_st43_fsm_42 = 7'b101010;
parameter    ap_ST_st44_fsm_43 = 7'b101011;
parameter    ap_ST_st45_fsm_44 = 7'b101100;
parameter    ap_ST_st46_fsm_45 = 7'b101101;
parameter    ap_ST_st47_fsm_46 = 7'b101110;
parameter    ap_ST_st48_fsm_47 = 7'b101111;
parameter    ap_ST_st49_fsm_48 = 7'b110000;
parameter    ap_ST_st50_fsm_49 = 7'b110001;
parameter    ap_ST_st51_fsm_50 = 7'b110010;
parameter    ap_ST_st52_fsm_51 = 7'b110011;
parameter    ap_ST_st53_fsm_52 = 7'b110100;
parameter    ap_ST_st54_fsm_53 = 7'b110101;
parameter    ap_ST_st55_fsm_54 = 7'b110110;
parameter    ap_ST_st56_fsm_55 = 7'b110111;
parameter    ap_ST_st57_fsm_56 = 7'b111000;
parameter    ap_ST_st58_fsm_57 = 7'b111001;
parameter    ap_ST_st59_fsm_58 = 7'b111010;
parameter    ap_ST_st60_fsm_59 = 7'b111011;
parameter    ap_ST_st61_fsm_60 = 7'b111100;
parameter    ap_ST_st62_fsm_61 = 7'b111101;
parameter    ap_ST_st63_fsm_62 = 7'b111110;
parameter    ap_ST_st64_fsm_63 = 7'b111111;
parameter    ap_ST_st65_fsm_64 = 7'b1000000;
parameter    ap_ST_st66_fsm_65 = 7'b1000001;
parameter    ap_ST_st67_fsm_66 = 7'b1000010;
parameter    ap_ST_st68_fsm_67 = 7'b1000011;
parameter    ap_ST_st69_fsm_68 = 7'b1000100;
parameter    ap_ST_st70_fsm_69 = 7'b1000101;
parameter    ap_ST_st71_fsm_70 = 7'b1000110;
parameter    ap_ST_st72_fsm_71 = 7'b1000111;
parameter    ap_ST_st73_fsm_72 = 7'b1001000;
parameter    ap_ST_st74_fsm_73 = 7'b1001001;
parameter    ap_ST_st75_fsm_74 = 7'b1001010;
parameter    ap_ST_st76_fsm_75 = 7'b1001011;
parameter    ap_ST_st77_fsm_76 = 7'b1001100;
parameter    ap_ST_st78_fsm_77 = 7'b1001101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;


bitset_next grp_bitset_next_fu_348(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .p_read( grp_bitset_next_fu_348_p_read ),
    .r_bit( grp_bitset_next_fu_348_r_bit ),
    .r_bucket_index( grp_bitset_next_fu_348_r_bucket_index ),
    .r_bucket( grp_bitset_next_fu_348_r_bucket ),
    .ap_return_0( grp_bitset_next_fu_348_ap_return_0 ),
    .ap_return_1( grp_bitset_next_fu_348_ap_return_1 ),
    .ap_return_2( grp_bitset_next_fu_348_ap_return_2 ),
    .ap_return_3( grp_bitset_next_fu_348_ap_return_3 ),
    .ap_ce( grp_bitset_next_fu_348_ap_ce )
);

nfa_get_initials grp_nfa_get_initials_fu_360(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_nfa_get_initials_fu_360_ap_start ),
    .ap_done( grp_nfa_get_initials_fu_360_ap_done ),
    .ap_idle( grp_nfa_get_initials_fu_360_ap_idle ),
    .ap_ready( grp_nfa_get_initials_fu_360_ap_ready ),
    .nfa_initials_buckets_req_din( grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_din ),
    .nfa_initials_buckets_req_full_n( grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_full_n ),
    .nfa_initials_buckets_req_write( grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_write ),
    .nfa_initials_buckets_rsp_empty_n( grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_empty_n ),
    .nfa_initials_buckets_rsp_read( grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_read ),
    .nfa_initials_buckets_address( grp_nfa_get_initials_fu_360_nfa_initials_buckets_address ),
    .nfa_initials_buckets_datain( grp_nfa_get_initials_fu_360_nfa_initials_buckets_datain ),
    .nfa_initials_buckets_dataout( grp_nfa_get_initials_fu_360_nfa_initials_buckets_dataout ),
    .nfa_initials_buckets_size( grp_nfa_get_initials_fu_360_nfa_initials_buckets_size ),
    .ap_ce( grp_nfa_get_initials_fu_360_ap_ce ),
    .ap_return_0( grp_nfa_get_initials_fu_360_ap_return_0 ),
    .ap_return_1( grp_nfa_get_initials_fu_360_ap_return_1 )
);

nfa_get_finals grp_nfa_get_finals_fu_366(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_nfa_get_finals_fu_366_ap_start ),
    .ap_done( grp_nfa_get_finals_fu_366_ap_done ),
    .ap_idle( grp_nfa_get_finals_fu_366_ap_idle ),
    .ap_ready( grp_nfa_get_finals_fu_366_ap_ready ),
    .nfa_finals_buckets_req_din( grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_din ),
    .nfa_finals_buckets_req_full_n( grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_full_n ),
    .nfa_finals_buckets_req_write( grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_write ),
    .nfa_finals_buckets_rsp_empty_n( grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_empty_n ),
    .nfa_finals_buckets_rsp_read( grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_read ),
    .nfa_finals_buckets_address( grp_nfa_get_finals_fu_366_nfa_finals_buckets_address ),
    .nfa_finals_buckets_datain( grp_nfa_get_finals_fu_366_nfa_finals_buckets_datain ),
    .nfa_finals_buckets_dataout( grp_nfa_get_finals_fu_366_nfa_finals_buckets_dataout ),
    .nfa_finals_buckets_size( grp_nfa_get_finals_fu_366_nfa_finals_buckets_size ),
    .ap_ce( grp_nfa_get_finals_fu_366_ap_ce ),
    .ap_return_0( grp_nfa_get_finals_fu_366_ap_return_0 ),
    .ap_return_1( grp_nfa_get_finals_fu_366_ap_return_1 )
);

p_bsf32_hw grp_p_bsf32_hw_fu_372(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .bus_r( grp_p_bsf32_hw_fu_372_bus_r ),
    .ap_return( grp_p_bsf32_hw_fu_372_ap_return ),
    .ap_ce( grp_p_bsf32_hw_fu_372_ap_ce )
);

nfa_accept_samples_generic_hw_add_64ns_64ns_64_16 #(
    .ID( 17 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
nfa_accept_samples_generic_hw_add_64ns_64ns_64_16_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_400_p0 ),
    .din1( grp_fu_400_p1 ),
    .ce( grp_fu_400_ce ),
    .dout( grp_fu_400_p2 )
);

nfa_accept_samples_generic_hw_add_16ns_16ns_16_4 #(
    .ID( 18 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
nfa_accept_samples_generic_hw_add_16ns_16ns_16_4_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_410_p0 ),
    .din1( grp_fu_410_p1 ),
    .ce( grp_fu_410_ce ),
    .dout( grp_fu_410_p2 )
);

nfa_accept_samples_generic_hw_add_64ns_64ns_64_16 #(
    .ID( 19 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
nfa_accept_samples_generic_hw_add_64ns_64ns_64_16_U19(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_422_p0 ),
    .din1( grp_fu_422_p1 ),
    .ce( grp_fu_422_ce ),
    .dout( grp_fu_422_p2 )
);

nfa_accept_samples_generic_hw_add_6ns_6ns_6_2 #(
    .ID( 20 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
nfa_accept_samples_generic_hw_add_6ns_6ns_6_2_U20(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_471_p0 ),
    .din1( grp_fu_471_p1 ),
    .ce( grp_fu_471_ce ),
    .dout( grp_fu_471_p2 )
);

nfa_accept_samples_generic_hw_mul_8ns_6ns_14_9 #(
    .ID( 21 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
nfa_accept_samples_generic_hw_mul_8ns_6ns_14_9_U21(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_484_p0 ),
    .din1( grp_fu_484_p1 ),
    .ce( grp_fu_484_ce ),
    .dout( grp_fu_484_p2 )
);

nfa_accept_samples_generic_hw_add_14ns_14ns_14_4 #(
    .ID( 22 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
nfa_accept_samples_generic_hw_add_14ns_14ns_14_4_U22(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_490_p0 ),
    .din1( grp_fu_490_p1 ),
    .ce( grp_fu_490_ce ),
    .dout( grp_fu_490_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_return_preg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_return_preg
    if (ap_rst == 1'b1) begin
        ap_return_preg <= ap_const_lv1_0;
    end else begin
        if ((ap_ST_st78_fsm_77 == ap_CS_fsm)) begin
            ap_return_preg <= p_0_reg_336;
        end
    end
end

/// grp_nfa_get_finals_fu_366_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_nfa_get_finals_fu_366_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_nfa_get_finals_fu_366_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_ST_st24_fsm_23 == ap_NS_fsm) & (ap_ST_st23_fsm_22 == ap_CS_fsm) & (tmp_s_reg_605 == ap_const_lv1_0))) begin
            grp_nfa_get_finals_fu_366_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_nfa_get_finals_fu_366_ap_ready)) begin
            grp_nfa_get_finals_fu_366_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st40_fsm_39 == ap_CS_fsm) & (tmp_19_1_i_reg_634 == ap_const_lv1_0))) begin
        agg_result_bucket_index_0_lcssa4_i_reg_194 <= ap_const_lv1_1;
    end else if (((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0) & (tmp_19_i_reg_620 == ap_const_lv1_0))) begin
        agg_result_bucket_index_0_lcssa4_i_reg_194 <= ap_const_lv1_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        any_reg_323 <= ap_const_lv1_0;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        any_reg_323 <= ap_const_lv1_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st40_fsm_39 == ap_CS_fsm) & (tmp_19_1_i_reg_634 == ap_const_lv1_0))) begin
        bus_assign_reg_182 <= next_buckets_1_reg_162;
    end else if (((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0) & (tmp_19_i_reg_620 == ap_const_lv1_0))) begin
        bus_assign_reg_182 <= next_buckets_0_reg_172;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st45_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & ~(ap_const_lv1_0 == any_phi_fu_328_p4))) begin
        i_reg_138 <= i_1_reg_609;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        i_reg_138 <= ap_const_lv16_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        j_bit1_reg_303 <= j_bit1_ph_cast_fu_448_p1;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        j_bit1_reg_303 <= j_bit_reg_693;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        j_bucket1_ph_reg_207 <= bus_assign_reg_182;
    end else if (((ap_ST_st40_fsm_39 == ap_CS_fsm) & ~(tmp_19_1_i_reg_634 == ap_const_lv1_0))) begin
        j_bucket1_ph_reg_207 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        j_bucket1_reg_282 <= j_bucket1_ph_reg_207;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        j_bucket1_reg_282 <= j_bucket_reg_703;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        j_bucket_index1_ph_reg_220 <= agg_result_bucket_index_0_lcssa4_i_cast_cast_fu_440_p1;
    end else if (((ap_ST_st40_fsm_39 == ap_CS_fsm) & ~(tmp_19_1_i_reg_634 == ap_const_lv1_0))) begin
        j_bucket_index1_ph_reg_220 <= ap_const_lv2_2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        j_bucket_index1_reg_293 <= j_bucket_index1_ph_cast_fu_444_p1;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        j_bucket_index1_reg_293 <= j_bucket_index_reg_698;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        j_end_ph_reg_242 <= ap_const_lv1_0;
    end else if (((ap_ST_st40_fsm_39 == ap_CS_fsm) & ~(tmp_19_1_i_reg_634 == ap_const_lv1_0))) begin
        j_end_ph_reg_242 <= ap_const_lv1_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        j_end_reg_313 <= j_end_ph_reg_242;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        j_end_reg_313 <= p_s_reg_708;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st45_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & ~(ap_const_lv1_0 == any_phi_fu_328_p4))) begin
        next_buckets_0_reg_172 <= tmp_buckets_0_3_reg_269;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        next_buckets_0_reg_172 <= current_buckets_0_reg_585;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st45_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & ~(ap_const_lv1_0 == any_phi_fu_328_p4))) begin
        next_buckets_1_reg_162 <= tmp_buckets_1_3_reg_256;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        next_buckets_1_reg_162 <= current_buckets_1_reg_590;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st45_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & ~(ap_const_lv1_0 == any_phi_fu_328_p4))) begin
        p_01_rec_reg_150 <= p_rec_reg_624;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        p_01_rec_reg_150 <= ap_const_lv64_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st45_fsm_44 == ap_CS_fsm) & ~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & (ap_const_lv1_0 == any_phi_fu_328_p4))) begin
        p_0_reg_336 <= ap_const_lv1_0;
    end else if ((ap_ST_st77_fsm_76 == ap_CS_fsm)) begin
        p_0_reg_336 <= tmp_2_reg_766;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_buckets_0_3_reg_269 <= ap_const_lv32_0;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        tmp_buckets_0_3_reg_269 <= next_buckets_0_1_reg_731;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_buckets_1_3_reg_256 <= ap_const_lv32_0;
    end else if ((ap_ST_st67_fsm_66 == ap_CS_fsm)) begin
        tmp_buckets_1_3_reg_256 <= next_buckets_1_1_fu_552_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st74_fsm_73 == ap_CS_fsm)) begin
        current_buckets_0_1_reg_751 <= current_buckets_0_1_fu_566_p2;
        current_buckets_1_1_reg_756 <= current_buckets_1_1_fu_571_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        current_buckets_0_reg_585 <= grp_nfa_get_initials_fu_360_ap_return_0;
        current_buckets_1_reg_590 <= grp_nfa_get_initials_fu_360_ap_return_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        i_1_reg_609 <= grp_fu_410_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        j_bit1_ph_reg_231 <= r_bit_reg_638;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st56_fsm_55 == ap_CS_fsm)) begin
        j_bit_reg_693 <= grp_bitset_next_fu_348_ap_return_0;
        j_bucket_index_reg_698 <= grp_bitset_next_fu_348_ap_return_1;
        j_bucket_reg_703 <= grp_bitset_next_fu_348_ap_return_2;
        p_s_reg_708 <= grp_bitset_next_fu_348_ap_return_3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0) & (ap_ST_st66_fsm_65 == ap_CS_fsm))) begin
        next_buckets_0_1_reg_731 <= next_buckets_0_1_fu_546_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0))) begin
        p_rec_reg_624 <= grp_fu_422_p2;
        sym_reg_629 <= sample_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st42_fsm_41 == ap_CS_fsm)) begin
        r_bit_reg_638 <= grp_p_bsf32_hw_fu_372_ap_return;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st65_fsm_64 == ap_CS_fsm) & ~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0)) | (~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0) & (ap_ST_st66_fsm_65 == ap_CS_fsm)))) begin
        reg_378 <= nfa_forward_buckets_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st24_fsm_23 == ap_CS_fsm)) begin
        sample_addr_1_reg_614 <= grp_fu_400_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        state_reg_673 <= grp_fu_471_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        tmp_14_cast_reg_600[0] <= tmp_14_cast_fu_390_p1[0];
tmp_14_cast_reg_600[1] <= tmp_14_cast_fu_390_p1[1];
tmp_14_cast_reg_600[2] <= tmp_14_cast_fu_390_p1[2];
tmp_14_cast_reg_600[3] <= tmp_14_cast_fu_390_p1[3];
tmp_14_cast_reg_600[4] <= tmp_14_cast_fu_390_p1[4];
tmp_14_cast_reg_600[5] <= tmp_14_cast_fu_390_p1[5];
tmp_14_cast_reg_600[6] <= tmp_14_cast_fu_390_p1[6];
tmp_14_cast_reg_600[7] <= tmp_14_cast_fu_390_p1[7];
tmp_14_cast_reg_600[8] <= tmp_14_cast_fu_390_p1[8];
tmp_14_cast_reg_600[9] <= tmp_14_cast_fu_390_p1[9];
tmp_14_cast_reg_600[10] <= tmp_14_cast_fu_390_p1[10];
tmp_14_cast_reg_600[11] <= tmp_14_cast_fu_390_p1[11];
tmp_14_cast_reg_600[12] <= tmp_14_cast_fu_390_p1[12];
tmp_14_cast_reg_600[13] <= tmp_14_cast_fu_390_p1[13];
tmp_14_cast_reg_600[14] <= tmp_14_cast_fu_390_p1[14];
tmp_14_cast_reg_600[15] <= tmp_14_cast_fu_390_p1[15];
tmp_14_cast_reg_600[16] <= tmp_14_cast_fu_390_p1[16];
tmp_14_cast_reg_600[17] <= tmp_14_cast_fu_390_p1[17];
tmp_14_cast_reg_600[18] <= tmp_14_cast_fu_390_p1[18];
tmp_14_cast_reg_600[19] <= tmp_14_cast_fu_390_p1[19];
tmp_14_cast_reg_600[20] <= tmp_14_cast_fu_390_p1[20];
tmp_14_cast_reg_600[21] <= tmp_14_cast_fu_390_p1[21];
tmp_14_cast_reg_600[22] <= tmp_14_cast_fu_390_p1[22];
tmp_14_cast_reg_600[23] <= tmp_14_cast_fu_390_p1[23];
tmp_14_cast_reg_600[24] <= tmp_14_cast_fu_390_p1[24];
tmp_14_cast_reg_600[25] <= tmp_14_cast_fu_390_p1[25];
tmp_14_cast_reg_600[26] <= tmp_14_cast_fu_390_p1[26];
tmp_14_cast_reg_600[27] <= tmp_14_cast_fu_390_p1[27];
tmp_14_cast_reg_600[28] <= tmp_14_cast_fu_390_p1[28];
tmp_14_cast_reg_600[29] <= tmp_14_cast_fu_390_p1[29];
tmp_14_cast_reg_600[30] <= tmp_14_cast_fu_390_p1[30];
tmp_14_cast_reg_600[31] <= tmp_14_cast_fu_390_p1[31];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0) & ~(tmp_19_i_reg_620 == ap_const_lv1_0))) begin
        tmp_19_1_i_reg_634 <= tmp_19_1_i_fu_434_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        tmp_19_i_reg_620 <= tmp_19_i_fu_428_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st75_fsm_74 == ap_CS_fsm)) begin
        tmp_1_reg_761 <= tmp_1_fu_576_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st76_fsm_75 == ap_CS_fsm)) begin
        tmp_2_reg_766 <= tmp_2_fu_580_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st55_fsm_54 == ap_CS_fsm)) begin
        tmp_6_i_reg_688 <= grp_fu_484_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st44_fsm_43 == ap_CS_fsm)) begin
        tmp_7_i_cast_reg_658[0] <= tmp_7_i_cast_fu_452_p1[0];
tmp_7_i_cast_reg_658[1] <= tmp_7_i_cast_fu_452_p1[1];
tmp_7_i_cast_reg_658[2] <= tmp_7_i_cast_fu_452_p1[2];
tmp_7_i_cast_reg_658[3] <= tmp_7_i_cast_fu_452_p1[3];
tmp_7_i_cast_reg_658[4] <= tmp_7_i_cast_fu_452_p1[4];
tmp_7_i_cast_reg_658[5] <= tmp_7_i_cast_fu_452_p1[5];
tmp_7_i_cast_reg_658[6] <= tmp_7_i_cast_fu_452_p1[6];
tmp_7_i_cast_reg_658[7] <= tmp_7_i_cast_fu_452_p1[7];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st59_fsm_58 == ap_CS_fsm)) begin
        tmp_8_i_reg_713 <= grp_fu_490_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st73_fsm_72 == ap_CS_fsm)) begin
        tmp_buckets_0_reg_741 <= grp_nfa_get_finals_fu_366_ap_return_0;
        tmp_buckets_1_reg_746 <= grp_nfa_get_finals_fu_366_ap_return_1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st9_fsm_8 == ap_CS_fsm)) begin
        tmp_s_reg_605 <= tmp_s_fu_405_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | (ap_ST_st78_fsm_77 == ap_CS_fsm))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st78_fsm_77 == ap_CS_fsm)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_return assign process. ///
always @ (ap_CS_fsm or p_0_reg_336 or ap_return_preg)
begin
    if ((ap_ST_st78_fsm_77 == ap_CS_fsm)) begin
        ap_return = p_0_reg_336;
    end else begin
        ap_return = ap_return_preg;
    end
end

/// grp_bitset_next_fu_348_ap_ce assign process. ///
always @ (ap_CS_fsm or j_end_phi_fu_316_p4)
begin
    if ((((ap_ST_st45_fsm_44 == ap_CS_fsm) & (ap_const_lv1_0 == j_end_phi_fu_316_p4)) | (ap_ST_st46_fsm_45 == ap_CS_fsm) | (ap_ST_st47_fsm_46 == ap_CS_fsm) | (ap_ST_st55_fsm_54 == ap_CS_fsm) | (ap_ST_st56_fsm_55 == ap_CS_fsm) | (ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st52_fsm_51 == ap_CS_fsm) | (ap_ST_st53_fsm_52 == ap_CS_fsm) | (ap_ST_st54_fsm_53 == ap_CS_fsm))) begin
        grp_bitset_next_fu_348_ap_ce = ap_const_logic_1;
    end else begin
        grp_bitset_next_fu_348_ap_ce = ap_const_logic_0;
    end
end

/// grp_fu_422_ce assign process. ///
always @ (ap_CS_fsm or sample_rsp_empty_n or tmp_s_reg_605)
begin
    if (((ap_ST_st38_fsm_37 == ap_CS_fsm) | ((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0)) | (ap_ST_st34_fsm_33 == ap_CS_fsm) | ((ap_ST_st24_fsm_23 == ap_CS_fsm) & ~(tmp_s_reg_605 == ap_const_lv1_0)) | (ap_ST_st25_fsm_24 == ap_CS_fsm) | (ap_ST_st26_fsm_25 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st30_fsm_29 == ap_CS_fsm) | (ap_ST_st31_fsm_30 == ap_CS_fsm) | (ap_ST_st32_fsm_31 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st36_fsm_35 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm))) begin
        grp_fu_422_ce = ap_const_logic_1;
    end else begin
        grp_fu_422_ce = ap_const_logic_0;
    end
end

/// grp_nfa_get_initials_fu_360_ap_start assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        grp_nfa_get_initials_fu_360_ap_start = ap_const_logic_1;
    end else begin
        grp_nfa_get_initials_fu_360_ap_start = ap_const_logic_0;
    end
end

/// grp_p_bsf32_hw_fu_372_ap_ce assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st41_fsm_40 == ap_CS_fsm))) begin
        grp_p_bsf32_hw_fu_372_ap_ce = ap_const_logic_1;
    end else begin
        grp_p_bsf32_hw_fu_372_ap_ce = ap_const_logic_0;
    end
end

/// nfa_forward_buckets_address assign process. ///
always @ (ap_CS_fsm or tmp_4_i_cast_fu_517_p1 or tmp_9_i_cast_fu_535_p1)
begin
    if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        nfa_forward_buckets_address = tmp_9_i_cast_fu_535_p1;
    end else if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        nfa_forward_buckets_address = tmp_4_i_cast_fu_517_p1;
    end else begin
        nfa_forward_buckets_address = 'bx;
    end
end

/// nfa_forward_buckets_req_write assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st60_fsm_59 == ap_CS_fsm) | (ap_ST_st61_fsm_60 == ap_CS_fsm))) begin
        nfa_forward_buckets_req_write = ap_const_logic_1;
    end else begin
        nfa_forward_buckets_req_write = ap_const_logic_0;
    end
end

/// nfa_forward_buckets_rsp_read assign process. ///
always @ (ap_CS_fsm or nfa_forward_buckets_rsp_empty_n)
begin
    if ((((ap_ST_st65_fsm_64 == ap_CS_fsm) & ~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0)) | (~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0) & (ap_ST_st66_fsm_65 == ap_CS_fsm)))) begin
        nfa_forward_buckets_rsp_read = ap_const_logic_1;
    end else begin
        nfa_forward_buckets_rsp_read = ap_const_logic_0;
    end
end

/// sample_req_write assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st34_fsm_33 == ap_CS_fsm)) begin
        sample_req_write = ap_const_logic_1;
    end else begin
        sample_req_write = ap_const_logic_0;
    end
end

/// sample_rsp_read assign process. ///
always @ (ap_CS_fsm or sample_rsp_empty_n)
begin
    if (((ap_ST_st39_fsm_38 == ap_CS_fsm) & ~(sample_rsp_empty_n == ap_const_logic_0))) begin
        sample_rsp_read = ap_const_logic_1;
    end else begin
        sample_rsp_read = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or nfa_forward_buckets_rsp_empty_n or sample_rsp_empty_n or tmp_s_reg_605 or tmp_19_i_reg_620 or tmp_19_1_i_reg_634 or j_end_phi_fu_316_p4 or any_phi_fu_328_p4)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
        ap_ST_st24_fsm_23 : 
            if ((tmp_s_reg_605 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st68_fsm_67;
            end else begin
                ap_NS_fsm = ap_ST_st25_fsm_24;
            end
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
        ap_ST_st27_fsm_26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
        ap_ST_st29_fsm_28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
        ap_ST_st30_fsm_29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
        ap_ST_st31_fsm_30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
        ap_ST_st32_fsm_31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
        ap_ST_st33_fsm_32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
        ap_ST_st34_fsm_33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
        ap_ST_st35_fsm_34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
        ap_ST_st36_fsm_35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
        ap_ST_st37_fsm_36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
        ap_ST_st38_fsm_37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
        ap_ST_st39_fsm_38 : 
            if ((~(sample_rsp_empty_n == ap_const_logic_0) & (tmp_19_i_reg_620 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st41_fsm_40;
            end else if ((~(sample_rsp_empty_n == ap_const_logic_0) & ~(tmp_19_i_reg_620 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st40_fsm_39;
            end else begin
                ap_NS_fsm = ap_ST_st39_fsm_38;
            end
        ap_ST_st40_fsm_39 : 
            if (~(tmp_19_1_i_reg_634 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st44_fsm_43;
            end else begin
                ap_NS_fsm = ap_ST_st41_fsm_40;
            end
        ap_ST_st41_fsm_40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
        ap_ST_st42_fsm_41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
        ap_ST_st43_fsm_42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
        ap_ST_st44_fsm_43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
        ap_ST_st45_fsm_44 : 
            if ((~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & ~(ap_const_lv1_0 == any_phi_fu_328_p4))) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else if ((~(ap_const_lv1_0 == j_end_phi_fu_316_p4) & (ap_const_lv1_0 == any_phi_fu_328_p4))) begin
                ap_NS_fsm = ap_ST_st78_fsm_77;
            end else begin
                ap_NS_fsm = ap_ST_st46_fsm_45;
            end
        ap_ST_st46_fsm_45 : 
            ap_NS_fsm = ap_ST_st47_fsm_46;
        ap_ST_st47_fsm_46 : 
            ap_NS_fsm = ap_ST_st48_fsm_47;
        ap_ST_st48_fsm_47 : 
            ap_NS_fsm = ap_ST_st49_fsm_48;
        ap_ST_st49_fsm_48 : 
            ap_NS_fsm = ap_ST_st50_fsm_49;
        ap_ST_st50_fsm_49 : 
            ap_NS_fsm = ap_ST_st51_fsm_50;
        ap_ST_st51_fsm_50 : 
            ap_NS_fsm = ap_ST_st52_fsm_51;
        ap_ST_st52_fsm_51 : 
            ap_NS_fsm = ap_ST_st53_fsm_52;
        ap_ST_st53_fsm_52 : 
            ap_NS_fsm = ap_ST_st54_fsm_53;
        ap_ST_st54_fsm_53 : 
            ap_NS_fsm = ap_ST_st55_fsm_54;
        ap_ST_st55_fsm_54 : 
            ap_NS_fsm = ap_ST_st56_fsm_55;
        ap_ST_st56_fsm_55 : 
            ap_NS_fsm = ap_ST_st57_fsm_56;
        ap_ST_st57_fsm_56 : 
            ap_NS_fsm = ap_ST_st58_fsm_57;
        ap_ST_st58_fsm_57 : 
            ap_NS_fsm = ap_ST_st59_fsm_58;
        ap_ST_st59_fsm_58 : 
            ap_NS_fsm = ap_ST_st60_fsm_59;
        ap_ST_st60_fsm_59 : 
            ap_NS_fsm = ap_ST_st61_fsm_60;
        ap_ST_st61_fsm_60 : 
            ap_NS_fsm = ap_ST_st62_fsm_61;
        ap_ST_st62_fsm_61 : 
            ap_NS_fsm = ap_ST_st63_fsm_62;
        ap_ST_st63_fsm_62 : 
            ap_NS_fsm = ap_ST_st64_fsm_63;
        ap_ST_st64_fsm_63 : 
            ap_NS_fsm = ap_ST_st65_fsm_64;
        ap_ST_st65_fsm_64 : 
            if (~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st66_fsm_65;
            end else begin
                ap_NS_fsm = ap_ST_st65_fsm_64;
            end
        ap_ST_st66_fsm_65 : 
            if (~(nfa_forward_buckets_rsp_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st67_fsm_66;
            end else begin
                ap_NS_fsm = ap_ST_st66_fsm_65;
            end
        ap_ST_st67_fsm_66 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
        ap_ST_st68_fsm_67 : 
            ap_NS_fsm = ap_ST_st69_fsm_68;
        ap_ST_st69_fsm_68 : 
            ap_NS_fsm = ap_ST_st70_fsm_69;
        ap_ST_st70_fsm_69 : 
            ap_NS_fsm = ap_ST_st71_fsm_70;
        ap_ST_st71_fsm_70 : 
            ap_NS_fsm = ap_ST_st72_fsm_71;
        ap_ST_st72_fsm_71 : 
            ap_NS_fsm = ap_ST_st73_fsm_72;
        ap_ST_st73_fsm_72 : 
            ap_NS_fsm = ap_ST_st74_fsm_73;
        ap_ST_st74_fsm_73 : 
            ap_NS_fsm = ap_ST_st75_fsm_74;
        ap_ST_st75_fsm_74 : 
            ap_NS_fsm = ap_ST_st76_fsm_75;
        ap_ST_st76_fsm_75 : 
            ap_NS_fsm = ap_ST_st77_fsm_76;
        ap_ST_st77_fsm_76 : 
            ap_NS_fsm = ap_ST_st78_fsm_77;
        ap_ST_st78_fsm_77 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign agg_result_bucket_index_0_lcssa4_i_cast_cast_fu_440_p1 = $unsigned(agg_result_bucket_index_0_lcssa4_i_reg_194);
assign any_phi_fu_328_p4 = any_reg_323;
assign current_buckets_0_1_fu_566_p2 = (next_buckets_0_reg_172 & tmp_buckets_0_reg_741);
assign current_buckets_1_1_fu_571_p2 = (next_buckets_1_reg_162 & tmp_buckets_1_reg_746);
assign grp_bitset_next_fu_348_p_read = next_buckets_1_reg_162;
assign grp_bitset_next_fu_348_r_bit = j_bit1_reg_303;
assign grp_bitset_next_fu_348_r_bucket = j_bucket1_reg_282;
assign grp_bitset_next_fu_348_r_bucket_index = j_bucket_index1_reg_293;
assign grp_fu_400_ce = ap_const_logic_1;
assign grp_fu_400_p0 = p_01_rec_reg_150;
assign grp_fu_400_p1 = tmp_14_cast_reg_600;
assign grp_fu_410_ce = ap_const_logic_1;
assign grp_fu_410_p0 = i_reg_138;
assign grp_fu_410_p1 = ap_const_lv16_1;
assign grp_fu_422_p0 = p_01_rec_reg_150;
assign grp_fu_422_p1 = ap_const_lv64_1;
assign grp_fu_471_ce = ap_const_logic_1;
assign grp_fu_471_p0 = {{tmp_31_fu_455_p1}, {ap_const_lv5_0}};
assign grp_fu_471_p1 = j_bit1_reg_303[5:0];
assign grp_fu_484_ce = ap_const_logic_1;
assign grp_fu_484_p0 = grp_fu_484_p00;
assign grp_fu_484_p00 = $unsigned(nfa_symbols);
assign grp_fu_484_p1 = grp_fu_484_p10;
assign grp_fu_484_p10 = $unsigned(state_reg_673);
assign grp_fu_490_ce = ap_const_logic_1;
assign grp_fu_490_p0 = tmp_6_i_reg_688;
assign grp_fu_490_p1 = tmp_7_i_cast_reg_658;
assign grp_nfa_get_finals_fu_366_ap_ce = ap_const_logic_1;
assign grp_nfa_get_finals_fu_366_ap_start = grp_nfa_get_finals_fu_366_ap_start_ap_start_reg;
assign grp_nfa_get_finals_fu_366_nfa_finals_buckets_datain = nfa_finals_buckets_datain;
assign grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_full_n = nfa_finals_buckets_req_full_n;
assign grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_empty_n = nfa_finals_buckets_rsp_empty_n;
assign grp_nfa_get_initials_fu_360_ap_ce = ap_const_logic_1;
assign grp_nfa_get_initials_fu_360_nfa_initials_buckets_datain = nfa_initials_buckets_datain;
assign grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_full_n = nfa_initials_buckets_req_full_n;
assign grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_empty_n = nfa_initials_buckets_rsp_empty_n;
assign grp_p_bsf32_hw_fu_372_bus_r = bus_assign_reg_182;
assign j_bit1_ph_cast_fu_448_p1 = $unsigned(j_bit1_ph_reg_231);
assign j_bucket_index1_ph_cast_fu_444_p1 = $unsigned(j_bucket_index1_ph_reg_220);
assign j_end_phi_fu_316_p4 = j_end_reg_313;
assign next_buckets_0_1_fu_546_p2 = (tmp_buckets_0_3_reg_269 | reg_378);
assign next_buckets_1_1_fu_552_p2 = (tmp_buckets_1_3_reg_256 | reg_378);
assign nfa_finals_buckets_address = grp_nfa_get_finals_fu_366_nfa_finals_buckets_address;
assign nfa_finals_buckets_dataout = grp_nfa_get_finals_fu_366_nfa_finals_buckets_dataout;
assign nfa_finals_buckets_req_din = grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_din;
assign nfa_finals_buckets_req_write = grp_nfa_get_finals_fu_366_nfa_finals_buckets_req_write;
assign nfa_finals_buckets_rsp_read = grp_nfa_get_finals_fu_366_nfa_finals_buckets_rsp_read;
assign nfa_finals_buckets_size = grp_nfa_get_finals_fu_366_nfa_finals_buckets_size;
assign nfa_forward_buckets_dataout = ap_const_lv32_0;
assign nfa_forward_buckets_req_din = ap_const_logic_0;
assign nfa_forward_buckets_size = ap_const_lv32_1;
assign nfa_initials_buckets_address = grp_nfa_get_initials_fu_360_nfa_initials_buckets_address;
assign nfa_initials_buckets_dataout = grp_nfa_get_initials_fu_360_nfa_initials_buckets_dataout;
assign nfa_initials_buckets_req_din = grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_din;
assign nfa_initials_buckets_req_write = grp_nfa_get_initials_fu_360_nfa_initials_buckets_req_write;
assign nfa_initials_buckets_rsp_read = grp_nfa_get_initials_fu_360_nfa_initials_buckets_rsp_read;
assign nfa_initials_buckets_size = grp_nfa_get_initials_fu_360_nfa_initials_buckets_size;
assign sample_address = sample_addr_1_reg_614;
assign sample_dataout = ap_const_lv8_0;
assign sample_req_din = ap_const_logic_0;
assign sample_size = ap_const_lv32_1;
assign tmp_14_cast_fu_390_p1 = $unsigned(tmp_14);
assign tmp_19_1_i_fu_434_p2 = (next_buckets_1_reg_162 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_19_i_fu_428_p2 = (next_buckets_0_reg_172 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_1_fu_576_p2 = (current_buckets_1_1_reg_756 | current_buckets_0_1_reg_751);
assign tmp_2_fu_580_p2 = (tmp_1_reg_761 != ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_31_fu_455_p1 = j_bucket_index1_reg_293[0:0];
assign tmp_4_i_cast_fu_517_p1 = $unsigned(tmp_4_i_fu_510_p3);
assign tmp_4_i_fu_510_p3 = {{tmp_8_i_reg_713}, {ap_const_lv1_0}};
assign tmp_7_i_cast_fu_452_p1 = $unsigned(sym_reg_629);
assign tmp_9_i_cast_fu_535_p1 = $unsigned(tmp_9_i_fu_528_p3);
assign tmp_9_i_fu_528_p3 = {{tmp_8_i_reg_713}, {ap_const_lv1_1}};
assign tmp_s_fu_405_p2 = (i_reg_138 < length_r? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    tmp_14_cast_reg_600[63:32] <= 32'b00000000000000000000000000000000;
    tmp_7_i_cast_reg_658[13:8] <= 6'b000000;
end



endmodule //nfa_accept_sample

