<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="10">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>nfa_accept_samples_generic_hw</name>
		<ret_bitwidth>32</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>18</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>nfa_initials_buckets</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>nfa.initials.buckets</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>nfa_finals_buckets</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>nfa.finals.buckets</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>nfa_forward_buckets</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>nfa.forward.buckets</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_4">
				<Value>
					<Obj>
						<type>1</type>
						<id>4</id>
						<name>nfa_backward_buckets</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>nfa.backward.buckets</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>3</direction>
				<if_type>1</if_type>
				<array_size>32130</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_5">
				<Value>
					<Obj>
						<type>1</type>
						<id>5</id>
						<name>nfa_symbols</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>nfa.symbols</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_6">
				<Value>
					<Obj>
						<type>1</type>
						<id>6</id>
						<name>sample_buffer</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>sample_buffer</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_7">
				<Value>
					<Obj>
						<type>1</type>
						<id>7</id>
						<name>sample_buffer_length</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>sample_buffer_length</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_8">
				<Value>
					<Obj>
						<type>1</type>
						<id>8</id>
						<name>sample_length</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>sample_length</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_9">
				<Value>
					<Obj>
						<type>1</type>
						<id>9</id>
						<name>indices_begin</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>indices.begin</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_10">
				<Value>
					<Obj>
						<type>1</type>
						<id>10</id>
						<name>indices_samples</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>indices.samples</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_11">
				<Value>
					<Obj>
						<type>1</type>
						<id>11</id>
						<name>indices_stride</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>indices.stride</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_12">
				<Value>
					<Obj>
						<type>1</type>
						<id>12</id>
						<name>i_size</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i_size</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_13">
				<Value>
					<Obj>
						<type>1</type>
						<id>13</id>
						<name>begin_index</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.index</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_14">
				<Value>
					<Obj>
						<type>1</type>
						<id>14</id>
						<name>begin_sample</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.sample</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_15">
				<Value>
					<Obj>
						<type>1</type>
						<id>15</id>
						<name>end_index</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_16">
				<Value>
					<Obj>
						<type>1</type>
						<id>16</id>
						<name>end_sample</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_17">
				<Value>
					<Obj>
						<type>1</type>
						<id>17</id>
						<name>stop_on_first</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>stop_on_first</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_18">
				<Value>
					<Obj>
						<type>1</type>
						<id>18</id>
						<name>accept</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>accept</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>32</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>c</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>c</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>112</item>
				</oprand_edges>
				<opcode>alloca</opcode>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name>accept_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>accept</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>114</item>
					<item>115</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>41</id>
						<name>stop_on_first_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>stop_on_first</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>116</item>
					<item>117</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>42</id>
						<name>end_sample_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>119</item>
					<item>120</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name>end_index_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>121</item>
					<item>122</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>44</id>
						<name>begin_sample_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>123</item>
					<item>124</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>45</id>
						<name>begin_index_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>125</item>
					<item>126</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name>sample_length_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>sample_length</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>127</item>
					<item>128</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>47</id>
						<name>sample_buffer_length_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>sample_buffer_length</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>130</item>
					<item>131</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_28">
				<Value>
					<Obj>
						<type>0</type>
						<id>77</id>
						<name></name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>133</item>
					<item>134</item>
				</oprand_edges>
				<opcode>store</opcode>
			</item>
			<item class_id_reference="9" object_id="_29">
				<Value>
					<Obj>
						<type>0</type>
						<id>78</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>c:/Design/XilinxHLS_ws</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>135</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_30">
				<Value>
					<Obj>
						<type>0</type>
						<id>80</id>
						<name>i_index</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.index</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>136</item>
					<item>137</item>
					<item>138</item>
					<item>139</item>
				</oprand_edges>
				<opcode>phi</opcode>
			</item>
			<item class_id_reference="9" object_id="_31">
				<Value>
					<Obj>
						<type>0</type>
						<id>81</id>
						<name>i_sample</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.sample</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>140</item>
					<item>141</item>
					<item>142</item>
					<item>143</item>
				</oprand_edges>
				<opcode>phi</opcode>
			</item>
			<item class_id_reference="9" object_id="_32">
				<Value>
					<Obj>
						<type>0</type>
						<id>82</id>
						<name>c_load</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>383</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>383</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>144</item>
					<item>511</item>
				</oprand_edges>
				<opcode>load</opcode>
			</item>
			<item class_id_reference="9" object_id="_33">
				<Value>
					<Obj>
						<type>0</type>
						<id>84</id>
						<name>tmp_i</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>254</lineNumber>
						<contextFuncName>sample_iterator_equals</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>sample_iterator_equals</second>
										</first>
										<second>254</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>145</item>
					<item>146</item>
				</oprand_edges>
				<opcode>icmp</opcode>
			</item>
			<item class_id_reference="9" object_id="_34">
				<Value>
					<Obj>
						<type>0</type>
						<id>85</id>
						<name>tmp_i_10</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>254</lineNumber>
						<contextFuncName>sample_iterator_equals</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>sample_iterator_equals</second>
										</first>
										<second>254</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>147</item>
					<item>148</item>
				</oprand_edges>
				<opcode>icmp</opcode>
			</item>
			<item class_id_reference="9" object_id="_35">
				<Value>
					<Obj>
						<type>0</type>
						<id>86</id>
						<name>tmp_i_11</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>254</lineNumber>
						<contextFuncName>sample_iterator_equals</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>sample_iterator_equals</second>
										</first>
										<second>254</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>149</item>
					<item>150</item>
				</oprand_edges>
				<opcode>and</opcode>
			</item>
			<item class_id_reference="9" object_id="_36">
				<Value>
					<Obj>
						<type>0</type>
						<id>87</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>151</item>
					<item>152</item>
					<item>153</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_37">
				<Value>
					<Obj>
						<type>0</type>
						<id>91</id>
						<name>offset</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>378</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>378</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>offset</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>8</count>
					<item_version>0</item_version>
					<item>155</item>
					<item>156</item>
					<item>157</item>
					<item>158</item>
					<item>159</item>
					<item>160</item>
					<item>161</item>
					<item>162</item>
				</oprand_edges>
				<opcode>call</opcode>
			</item>
			<item class_id_reference="9" object_id="_38">
				<Value>
					<Obj>
						<type>0</type>
						<id>92</id>
						<name>r</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>379</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>379</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>r</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>8</count>
					<item_version>0</item_version>
					<item>164</item>
					<item>165</item>
					<item>166</item>
					<item>167</item>
					<item>168</item>
					<item>169</item>
					<item>170</item>
					<item>171</item>
				</oprand_edges>
				<opcode>call</opcode>
			</item>
			<item class_id_reference="9" object_id="_39">
				<Value>
					<Obj>
						<type>0</type>
						<id>93</id>
						<name>or_cond</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>380</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>380</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>172</item>
					<item>173</item>
				</oprand_edges>
				<opcode>xor</opcode>
			</item>
			<item class_id_reference="9" object_id="_40">
				<Value>
					<Obj>
						<type>0</type>
						<id>94</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>380</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>380</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>174</item>
					<item>175</item>
					<item>176</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_41">
				<Value>
					<Obj>
						<type>0</type>
						<id>96</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>382</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>382</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>177</item>
					<item>178</item>
					<item>179</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_42">
				<Value>
					<Obj>
						<type>0</type>
						<id>98</id>
						<name>c_1</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>383</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>383</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>c</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>180</item>
					<item>181</item>
				</oprand_edges>
				<opcode>add</opcode>
			</item>
			<item class_id_reference="9" object_id="_43">
				<Value>
					<Obj>
						<type>0</type>
						<id>99</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>383</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>383</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>182</item>
					<item>183</item>
					<item>512</item>
					<item>513</item>
				</oprand_edges>
				<opcode>store</opcode>
			</item>
			<item class_id_reference="9" object_id="_44">
				<Value>
					<Obj>
						<type>0</type>
						<id>100</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>384</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>384</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>184</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_45">
				<Value>
					<Obj>
						<type>0</type>
						<id>103</id>
						<name>call_ret</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>8</count>
					<item_version>0</item_version>
					<item>186</item>
					<item>187</item>
					<item>188</item>
					<item>189</item>
					<item>190</item>
					<item>191</item>
					<item>514</item>
					<item>515</item>
				</oprand_edges>
				<opcode>call</opcode>
			</item>
			<item class_id_reference="9" object_id="_46">
				<Value>
					<Obj>
						<type>0</type>
						<id>104</id>
						<name>i_index_1</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>i.index</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>192</item>
				</oprand_edges>
				<opcode>extractvalue</opcode>
			</item>
			<item class_id_reference="9" object_id="_47">
				<Value>
					<Obj>
						<type>0</type>
						<id>105</id>
						<name>i_sample_1</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>i.sample</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>193</item>
				</oprand_edges>
				<opcode>extractvalue</opcode>
			</item>
			<item class_id_reference="9" object_id="_48">
				<Value>
					<Obj>
						<type>0</type>
						<id>106</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>375</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>375</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>194</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_49">
				<Value>
					<Obj>
						<type>0</type>
						<id>108</id>
						<name>p_0</name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>383</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>383</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>195</item>
					<item>196</item>
					<item>197</item>
					<item>198</item>
				</oprand_edges>
				<opcode>phi</opcode>
			</item>
			<item class_id_reference="9" object_id="_50">
				<Value>
					<Obj>
						<type>0</type>
						<id>109</id>
						<name></name>
						<fileName>oil_plainc_hls/src/nfa.c</fileName>
						<fileDirectory>c:/Design/XilinxHLS_ws</fileDirectory>
						<lineNumber>387</lineNumber>
						<contextFuncName>nfa_accept_samples_generic_hw</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>c:/Design/XilinxHLS_ws</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>oil_plainc_hls/src/nfa.c</first>
											<second>nfa_accept_samples_generic_hw</second>
										</first>
										<second>387</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>199</item>
				</oprand_edges>
				<opcode>ret</opcode>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>5</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_51">
				<Value>
					<Obj>
						<type>2</type>
						<id>111</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_52">
				<Value>
					<Obj>
						<type>2</type>
						<id>132</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_53">
				<Value>
					<Obj>
						<type>2</type>
						<id>154</id>
						<name>sample_iterator_get_offset</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:sample_iterator_get_offset&gt;</content>
			</item>
			<item class_id_reference="16" object_id="_54">
				<Value>
					<Obj>
						<type>2</type>
						<id>163</id>
						<name>nfa_accept_sample</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:nfa_accept_sample&gt;</content>
			</item>
			<item class_id_reference="16" object_id="_55">
				<Value>
					<Obj>
						<type>2</type>
						<id>185</id>
						<name>sample_iterator_next</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:sample_iterator_next&gt;</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>7</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_56">
				<Obj>
					<type>3</type>
					<id>79</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>11</count>
					<item_version>0</item_version>
					<item>19</item>
					<item>40</item>
					<item>41</item>
					<item>42</item>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
					<item>47</item>
					<item>77</item>
					<item>78</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_57">
				<Obj>
					<type>3</type>
					<id>88</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>7</count>
					<item_version>0</item_version>
					<item>80</item>
					<item>81</item>
					<item>82</item>
					<item>84</item>
					<item>85</item>
					<item>86</item>
					<item>87</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_58">
				<Obj>
					<type>3</type>
					<id>95</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>91</item>
					<item>92</item>
					<item>93</item>
					<item>94</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_59">
				<Obj>
					<type>3</type>
					<id>97</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>96</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_60">
				<Obj>
					<type>3</type>
					<id>101</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>3</count>
					<item_version>0</item_version>
					<item>98</item>
					<item>99</item>
					<item>100</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_61">
				<Obj>
					<type>3</type>
					<id>107</id>
					<name>._crit_edge3</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>103</item>
					<item>104</item>
					<item>105</item>
					<item>106</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_62">
				<Obj>
					<type>3</type>
					<id>110</id>
					<name>._crit_edge</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>2</count>
					<item_version>0</item_version>
					<item>108</item>
					<item>109</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>87</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_63">
				<id>112</id>
				<edge_type>1</edge_type>
				<source_obj>111</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>115</id>
				<edge_type>1</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>117</id>
				<edge_type>1</edge_type>
				<source_obj>17</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>120</id>
				<edge_type>1</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>122</id>
				<edge_type>1</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>124</id>
				<edge_type>1</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>126</id>
				<edge_type>1</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>128</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>131</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>133</id>
				<edge_type>1</edge_type>
				<source_obj>132</source_obj>
				<sink_obj>77</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>134</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>77</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>135</id>
				<edge_type>2</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>78</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>136</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>80</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>137</id>
				<edge_type>2</edge_type>
				<source_obj>79</source_obj>
				<sink_obj>80</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>138</id>
				<edge_type>1</edge_type>
				<source_obj>104</source_obj>
				<sink_obj>80</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>139</id>
				<edge_type>2</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>80</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>140</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>81</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>141</id>
				<edge_type>2</edge_type>
				<source_obj>79</source_obj>
				<sink_obj>81</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>142</id>
				<edge_type>1</edge_type>
				<source_obj>105</source_obj>
				<sink_obj>81</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>143</id>
				<edge_type>2</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>81</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>144</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>82</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>145</id>
				<edge_type>1</edge_type>
				<source_obj>81</source_obj>
				<sink_obj>84</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>146</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>84</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_86">
				<id>147</id>
				<edge_type>1</edge_type>
				<source_obj>80</source_obj>
				<sink_obj>85</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_87">
				<id>148</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>85</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_88">
				<id>149</id>
				<edge_type>1</edge_type>
				<source_obj>84</source_obj>
				<sink_obj>86</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_89">
				<id>150</id>
				<edge_type>1</edge_type>
				<source_obj>85</source_obj>
				<sink_obj>86</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_90">
				<id>151</id>
				<edge_type>1</edge_type>
				<source_obj>86</source_obj>
				<sink_obj>87</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_91">
				<id>152</id>
				<edge_type>2</edge_type>
				<source_obj>95</source_obj>
				<sink_obj>87</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_92">
				<id>153</id>
				<edge_type>2</edge_type>
				<source_obj>110</source_obj>
				<sink_obj>87</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_93">
				<id>155</id>
				<edge_type>1</edge_type>
				<source_obj>154</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_94">
				<id>156</id>
				<edge_type>1</edge_type>
				<source_obj>80</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_95">
				<id>157</id>
				<edge_type>1</edge_type>
				<source_obj>81</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_96">
				<id>158</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_97">
				<id>159</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_98">
				<id>160</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_99">
				<id>161</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_100">
				<id>162</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>91</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_101">
				<id>164</id>
				<edge_type>1</edge_type>
				<source_obj>163</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_102">
				<id>165</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_103">
				<id>166</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_104">
				<id>167</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_105">
				<id>168</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_106">
				<id>169</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_107">
				<id>170</id>
				<edge_type>1</edge_type>
				<source_obj>91</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_108">
				<id>171</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>92</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_109">
				<id>172</id>
				<edge_type>1</edge_type>
				<source_obj>92</source_obj>
				<sink_obj>93</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_110">
				<id>173</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>93</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_111">
				<id>174</id>
				<edge_type>1</edge_type>
				<source_obj>93</source_obj>
				<sink_obj>94</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_112">
				<id>175</id>
				<edge_type>2</edge_type>
				<source_obj>97</source_obj>
				<sink_obj>94</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_113">
				<id>176</id>
				<edge_type>2</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>94</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_114">
				<id>177</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>96</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_115">
				<id>178</id>
				<edge_type>2</edge_type>
				<source_obj>101</source_obj>
				<sink_obj>96</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_116">
				<id>179</id>
				<edge_type>2</edge_type>
				<source_obj>110</source_obj>
				<sink_obj>96</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_117">
				<id>180</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>98</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_118">
				<id>181</id>
				<edge_type>1</edge_type>
				<source_obj>111</source_obj>
				<sink_obj>98</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_119">
				<id>182</id>
				<edge_type>1</edge_type>
				<source_obj>98</source_obj>
				<sink_obj>99</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_120">
				<id>183</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>99</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_121">
				<id>184</id>
				<edge_type>2</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>100</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_122">
				<id>186</id>
				<edge_type>1</edge_type>
				<source_obj>185</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_123">
				<id>187</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_124">
				<id>188</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_125">
				<id>189</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_126">
				<id>190</id>
				<edge_type>1</edge_type>
				<source_obj>80</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_127">
				<id>191</id>
				<edge_type>1</edge_type>
				<source_obj>81</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_128">
				<id>192</id>
				<edge_type>1</edge_type>
				<source_obj>103</source_obj>
				<sink_obj>104</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_129">
				<id>193</id>
				<edge_type>1</edge_type>
				<source_obj>103</source_obj>
				<sink_obj>105</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_130">
				<id>194</id>
				<edge_type>2</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>106</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_131">
				<id>195</id>
				<edge_type>1</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>108</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_132">
				<id>196</id>
				<edge_type>2</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>108</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_133">
				<id>197</id>
				<edge_type>1</edge_type>
				<source_obj>111</source_obj>
				<sink_obj>108</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_134">
				<id>198</id>
				<edge_type>2</edge_type>
				<source_obj>97</source_obj>
				<sink_obj>108</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_135">
				<id>199</id>
				<edge_type>1</edge_type>
				<source_obj>108</source_obj>
				<sink_obj>109</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_136">
				<id>502</id>
				<edge_type>2</edge_type>
				<source_obj>79</source_obj>
				<sink_obj>88</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_137">
				<id>503</id>
				<edge_type>2</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>110</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_138">
				<id>504</id>
				<edge_type>2</edge_type>
				<source_obj>88</source_obj>
				<sink_obj>95</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_139">
				<id>505</id>
				<edge_type>2</edge_type>
				<source_obj>95</source_obj>
				<sink_obj>107</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_140">
				<id>506</id>
				<edge_type>2</edge_type>
				<source_obj>95</source_obj>
				<sink_obj>97</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_141">
				<id>507</id>
				<edge_type>2</edge_type>
				<source_obj>97</source_obj>
				<sink_obj>110</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_142">
				<id>508</id>
				<edge_type>2</edge_type>
				<source_obj>97</source_obj>
				<sink_obj>101</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_143">
				<id>509</id>
				<edge_type>2</edge_type>
				<source_obj>101</source_obj>
				<sink_obj>107</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_144">
				<id>510</id>
				<edge_type>2</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>88</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_145">
				<id>511</id>
				<edge_type>4</edge_type>
				<source_obj>77</source_obj>
				<sink_obj>82</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_146">
				<id>512</id>
				<edge_type>4</edge_type>
				<source_obj>77</source_obj>
				<sink_obj>99</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_147">
				<id>513</id>
				<edge_type>4</edge_type>
				<source_obj>82</source_obj>
				<sink_obj>99</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_148">
				<id>514</id>
				<edge_type>4</edge_type>
				<source_obj>91</source_obj>
				<sink_obj>103</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_149">
				<id>515</id>
				<edge_type>4</edge_type>
				<source_obj>91</source_obj>
				<sink_obj>103</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>4</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_150">
			<mId>1</mId>
			<mTag>nfa_accept_samples_generic_hw</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>4</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>1412541395</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_151">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>79</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_152">
			<mId>3</mId>
			<mTag>Loop 1</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>5</count>
				<item_version>0</item_version>
				<item>88</item>
				<item>95</item>
				<item>97</item>
				<item>101</item>
				<item>107</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>0</mMinTripCount>
			<mMaxTripCount>65535</mMaxTripCount>
			<mMinLatency>1412541393</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_153">
			<mId>4</mId>
			<mTag>Return</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>110</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="25" tracking_level="1" version="0" object_id="_154">
		<dp_component_resource class_id="26" tracking_level="0" version="0">
			<count>0</count>
			<item_version>0</item_version>
		</dp_component_resource>
		<dp_expression_resource>
			<count>0</count>
			<item_version>0</item_version>
		</dp_expression_resource>
		<dp_fifo_resource>
			<count>0</count>
			<item_version>0</item_version>
		</dp_fifo_resource>
		<dp_memory_resource>
			<count>0</count>
			<item_version>0</item_version>
		</dp_memory_resource>
		<dp_multiplexer_resource>
			<count>0</count>
			<item_version>0</item_version>
		</dp_multiplexer_resource>
		<dp_register_resource>
			<count>0</count>
			<item_version>0</item_version>
		</dp_register_resource>
		<dp_component_map class_id="27" tracking_level="0" version="0">
			<count>0</count>
			<item_version>0</item_version>
		</dp_component_map>
		<dp_expression_map>
			<count>0</count>
			<item_version>0</item_version>
		</dp_expression_map>
		<dp_fifo_map>
			<count>0</count>
			<item_version>0</item_version>
		</dp_fifo_map>
		<dp_memory_map>
			<count>0</count>
			<item_version>0</item_version>
		</dp_memory_map>
	</res>
	<node_label_latency class_id="28" tracking_level="0" version="0">
		<count>32</count>
		<item_version>0</item_version>
		<item class_id="29" tracking_level="0" version="0">
			<first>19</first>
			<second class_id="30" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>41</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>42</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>45</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>47</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>77</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>78</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>80</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>81</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>82</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>84</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>85</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>86</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>87</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>91</first>
			<second>
				<first>3</first>
				<second>18</second>
			</second>
		</item>
		<item>
			<first>92</first>
			<second>
				<first>21</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>93</first>
			<second>
				<first>23</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>94</first>
			<second>
				<first>23</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>96</first>
			<second>
				<first>23</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>98</first>
			<second>
				<first>23</first>
				<second>7</second>
			</second>
		</item>
		<item>
			<first>99</first>
			<second>
				<first>31</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>100</first>
			<second>
				<first>31</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>103</first>
			<second>
				<first>31</first>
				<second>7</second>
			</second>
		</item>
		<item>
			<first>104</first>
			<second>
				<first>38</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>105</first>
			<second>
				<first>38</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>106</first>
			<second>
				<first>38</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>108</first>
			<second>
				<first>24</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>109</first>
			<second>
				<first>24</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="31" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="32" tracking_level="0" version="0">
			<first>79</first>
			<second class_id="33" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>88</first>
			<second>
				<first>1</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>95</first>
			<second>
				<first>3</first>
				<second>23</second>
			</second>
		</item>
		<item>
			<first>97</first>
			<second>
				<first>23</first>
				<second>23</second>
			</second>
		</item>
		<item>
			<first>101</first>
			<second>
				<first>23</first>
				<second>31</second>
			</second>
		</item>
		<item>
			<first>107</first>
			<second>
				<first>31</first>
				<second>38</second>
			</second>
		</item>
		<item>
			<first>110</first>
			<second>
				<first>24</first>
				<second>24</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</regions>
	<dp_fu_nodes class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="39" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

