-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2013.4
-- Copyright (C) 2013 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sample_iterator_get_offset is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    indices_stride_req_din : OUT STD_LOGIC;
    indices_stride_req_full_n : IN STD_LOGIC;
    indices_stride_req_write : OUT STD_LOGIC;
    indices_stride_rsp_empty_n : IN STD_LOGIC;
    indices_stride_rsp_read : OUT STD_LOGIC;
    indices_stride_address : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_stride_datain : IN STD_LOGIC_VECTOR (7 downto 0);
    indices_stride_dataout : OUT STD_LOGIC_VECTOR (7 downto 0);
    indices_stride_size : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_begin_req_din : OUT STD_LOGIC;
    indices_begin_req_full_n : IN STD_LOGIC;
    indices_begin_req_write : OUT STD_LOGIC;
    indices_begin_rsp_empty_n : IN STD_LOGIC;
    indices_begin_rsp_read : OUT STD_LOGIC;
    indices_begin_address : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_begin_datain : IN STD_LOGIC_VECTOR (31 downto 0);
    indices_begin_dataout : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_begin_size : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC;
    i_index : IN STD_LOGIC_VECTOR (15 downto 0);
    i_sample : IN STD_LOGIC_VECTOR (15 downto 0);
    indices_samples_req_din : OUT STD_LOGIC;
    indices_samples_req_full_n : IN STD_LOGIC;
    indices_samples_req_write : OUT STD_LOGIC;
    indices_samples_rsp_empty_n : IN STD_LOGIC;
    indices_samples_rsp_read : OUT STD_LOGIC;
    indices_samples_address : OUT STD_LOGIC_VECTOR (31 downto 0);
    indices_samples_datain : IN STD_LOGIC_VECTOR (15 downto 0);
    indices_samples_dataout : OUT STD_LOGIC_VECTOR (15 downto 0);
    indices_samples_size : OUT STD_LOGIC_VECTOR (31 downto 0);
    sample_buffer_size : IN STD_LOGIC_VECTOR (31 downto 0);
    sample_length : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of sample_iterator_get_offset is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_pp0_stg0_fsm_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it5 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it6 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it7 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it8 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it9 : STD_LOGIC := '0';
    signal i_sample_read_reg_131 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_ppstg_i_sample_read_reg_131_pp0_it1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_ppstg_i_sample_read_reg_131_pp0_it2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_ppstg_i_sample_read_reg_131_pp0_it3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_ppstg_i_sample_read_reg_131_pp0_it4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_reg_ppstg_i_sample_read_reg_131_pp0_it5 : STD_LOGIC_VECTOR (15 downto 0);
    signal indices_begin_addr_reg_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2 : STD_LOGIC_VECTOR (31 downto 0);
    signal indices_stride_addr_read_reg_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal indices_begin_addr_read_reg_163 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_93_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_116_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_116_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_116_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_8_cast_fu_122_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_116_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_pprstidle_pp0 : STD_LOGIC;
    signal grp_fu_116_p00 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_116_p10 : STD_LOGIC_VECTOR (23 downto 0);

    component nfa_accept_samples_generic_hw_mul_16ns_8ns_24_4 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;



begin
    nfa_accept_samples_generic_hw_mul_16ns_8ns_24_4_U0 : component nfa_accept_samples_generic_hw_mul_16ns_8ns_24_4
    generic map (
        ID => 0,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_116_p0,
        din1 => grp_fu_116_p1,
        ce => grp_fu_116_ce,
        dout => grp_fu_116_p2);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it3 assign process. --
    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it4 assign process. --
    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it5 assign process. --
    ap_reg_ppiten_pp0_it5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it6 assign process. --
    ap_reg_ppiten_pp0_it6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it7 assign process. --
    ap_reg_ppiten_pp0_it7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it8 assign process. --
    ap_reg_ppiten_pp0_it8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it9 assign process. --
    ap_reg_ppiten_pp0_it9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
                end if; 
            end if;
        end if;
    end process;


    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then
                ap_reg_ppstg_i_sample_read_reg_131_pp0_it1 <= i_sample_read_reg_131;
                ap_reg_ppstg_i_sample_read_reg_131_pp0_it2 <= ap_reg_ppstg_i_sample_read_reg_131_pp0_it1;
                ap_reg_ppstg_i_sample_read_reg_131_pp0_it3 <= ap_reg_ppstg_i_sample_read_reg_131_pp0_it2;
                ap_reg_ppstg_i_sample_read_reg_131_pp0_it4 <= ap_reg_ppstg_i_sample_read_reg_131_pp0_it3;
                ap_reg_ppstg_i_sample_read_reg_131_pp0_it5 <= ap_reg_ppstg_i_sample_read_reg_131_pp0_it4;
                ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(0) <= indices_begin_addr_reg_136(0);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(1) <= indices_begin_addr_reg_136(1);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(2) <= indices_begin_addr_reg_136(2);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(3) <= indices_begin_addr_reg_136(3);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(4) <= indices_begin_addr_reg_136(4);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(5) <= indices_begin_addr_reg_136(5);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(6) <= indices_begin_addr_reg_136(6);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(7) <= indices_begin_addr_reg_136(7);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(8) <= indices_begin_addr_reg_136(8);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(9) <= indices_begin_addr_reg_136(9);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(10) <= indices_begin_addr_reg_136(10);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(11) <= indices_begin_addr_reg_136(11);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(12) <= indices_begin_addr_reg_136(12);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(13) <= indices_begin_addr_reg_136(13);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(14) <= indices_begin_addr_reg_136(14);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(15) <= indices_begin_addr_reg_136(15);
                ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(0) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(0);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(1) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(1);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(2) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(2);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(3) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(3);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(4) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(4);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(5) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(5);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(6) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(6);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(7) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(7);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(8) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(8);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(9) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(9);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(10) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(10);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(11) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(11);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(12) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(12);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(13) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(13);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(14) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(14);
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(15) <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(15);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then
                i_sample_read_reg_131 <= i_sample;
                indices_begin_addr_reg_136(0) <= tmp_fu_93_p1(32 - 1 downto 0)(0);
    indices_begin_addr_reg_136(1) <= tmp_fu_93_p1(32 - 1 downto 0)(1);
    indices_begin_addr_reg_136(2) <= tmp_fu_93_p1(32 - 1 downto 0)(2);
    indices_begin_addr_reg_136(3) <= tmp_fu_93_p1(32 - 1 downto 0)(3);
    indices_begin_addr_reg_136(4) <= tmp_fu_93_p1(32 - 1 downto 0)(4);
    indices_begin_addr_reg_136(5) <= tmp_fu_93_p1(32 - 1 downto 0)(5);
    indices_begin_addr_reg_136(6) <= tmp_fu_93_p1(32 - 1 downto 0)(6);
    indices_begin_addr_reg_136(7) <= tmp_fu_93_p1(32 - 1 downto 0)(7);
    indices_begin_addr_reg_136(8) <= tmp_fu_93_p1(32 - 1 downto 0)(8);
    indices_begin_addr_reg_136(9) <= tmp_fu_93_p1(32 - 1 downto 0)(9);
    indices_begin_addr_reg_136(10) <= tmp_fu_93_p1(32 - 1 downto 0)(10);
    indices_begin_addr_reg_136(11) <= tmp_fu_93_p1(32 - 1 downto 0)(11);
    indices_begin_addr_reg_136(12) <= tmp_fu_93_p1(32 - 1 downto 0)(12);
    indices_begin_addr_reg_136(13) <= tmp_fu_93_p1(32 - 1 downto 0)(13);
    indices_begin_addr_reg_136(14) <= tmp_fu_93_p1(32 - 1 downto 0)(14);
    indices_begin_addr_reg_136(15) <= tmp_fu_93_p1(32 - 1 downto 0)(15);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then
                indices_begin_addr_read_reg_163 <= indices_begin_datain;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then
                indices_stride_addr_read_reg_148 <= indices_stride_datain;
            end if;
        end if;
    end process;
    indices_begin_addr_reg_136(31 downto 16) <= "0000000000000000";
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it1(31 downto 16) <= "0000000000000000";
    ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2(31 downto 16) <= "0000000000000000";

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_start , ap_CS_fsm , ap_reg_ppiten_pp0_it0 , ap_reg_ppiten_pp0_it5 , ap_reg_ppiten_pp0_it8 , indices_stride_rsp_empty_n , indices_begin_rsp_empty_n , ap_ce , ap_sig_pprstidle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_pp0_stg0_fsm_0 => 
                ap_NS_fsm <= ap_ST_pp0_stg0_fsm_0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, ap_reg_ppiten_pp0_it9, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((not((ap_const_logic_1 = ap_start)) and (ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0)) or ((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it9) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it3, ap_reg_ppiten_pp0_it4, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it6, ap_reg_ppiten_pp0_it7, ap_reg_ppiten_pp0_it8, ap_reg_ppiten_pp0_it9)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it2) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it3) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it4) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it5) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it6) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it7) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it8) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it9))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_reg_ppiten_pp0_it0 <= ap_start;
    ap_return <= std_logic_vector(unsigned(tmp_8_cast_fu_122_p1) + unsigned(indices_begin_addr_read_reg_163));

    -- ap_sig_pprstidle_pp0 assign process. --
    ap_sig_pprstidle_pp0_assign_proc : process(ap_start, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it3, ap_reg_ppiten_pp0_it4, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it6, ap_reg_ppiten_pp0_it7, ap_reg_ppiten_pp0_it8)
    begin
        if (((ap_const_logic_0 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it2) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it3) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it4) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it5) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it6) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it7) and (ap_const_logic_0 = ap_reg_ppiten_pp0_it8) and (ap_const_logic_0 = ap_start))) then 
            ap_sig_pprstidle_pp0 <= ap_const_logic_1;
        else 
            ap_sig_pprstidle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    -- grp_fu_116_ce assign process. --
    grp_fu_116_ce_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            grp_fu_116_ce <= ap_const_logic_1;
        else 
            grp_fu_116_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_116_p0 <= grp_fu_116_p00(16 - 1 downto 0);
    grp_fu_116_p00 <= std_logic_vector(resize(unsigned(ap_reg_ppstg_i_sample_read_reg_131_pp0_it5),24));
    grp_fu_116_p1 <= grp_fu_116_p10(8 - 1 downto 0);
    grp_fu_116_p10 <= std_logic_vector(resize(unsigned(indices_stride_addr_read_reg_148),24));
    indices_begin_address <= ap_reg_ppstg_indices_begin_addr_reg_136_pp0_it2;
    indices_begin_dataout <= ap_const_lv32_0;
    indices_begin_req_din <= ap_const_logic_0;

    -- indices_begin_req_write assign process. --
    indices_begin_req_write_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it3, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            indices_begin_req_write <= ap_const_logic_1;
        else 
            indices_begin_req_write <= ap_const_logic_0;
        end if; 
    end process;


    -- indices_begin_rsp_read assign process. --
    indices_begin_rsp_read_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            indices_begin_rsp_read <= ap_const_logic_1;
        else 
            indices_begin_rsp_read <= ap_const_logic_0;
        end if; 
    end process;

    indices_begin_size <= ap_const_lv32_1;
    indices_samples_address <= ap_const_lv32_0;
    indices_samples_dataout <= ap_const_lv16_0;
    indices_samples_req_din <= ap_const_logic_0;
    indices_samples_req_write <= ap_const_logic_0;
    indices_samples_rsp_read <= ap_const_logic_0;
    indices_samples_size <= ap_const_lv32_0;
    indices_stride_address <= tmp_fu_93_p1(32 - 1 downto 0);
    indices_stride_dataout <= ap_const_lv8_0;
    indices_stride_req_din <= ap_const_logic_0;

    -- indices_stride_req_write assign process. --
    indices_stride_req_write_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            indices_stride_req_write <= ap_const_logic_1;
        else 
            indices_stride_req_write <= ap_const_logic_0;
        end if; 
    end process;


    -- indices_stride_rsp_read assign process. --
    indices_stride_rsp_read_assign_proc : process(ap_start, ap_CS_fsm, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it5, ap_reg_ppiten_pp0_it8, indices_stride_rsp_empty_n, indices_begin_rsp_empty_n, ap_ce)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_start = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and (indices_stride_rsp_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and (indices_begin_rsp_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_ce))) then 
            indices_stride_rsp_read <= ap_const_logic_1;
        else 
            indices_stride_rsp_read <= ap_const_logic_0;
        end if; 
    end process;

    indices_stride_size <= ap_const_lv32_1;
    tmp_8_cast_fu_122_p1 <= std_logic_vector(resize(unsigned(grp_fu_116_p2),32));
    tmp_fu_93_p1 <= std_logic_vector(resize(unsigned(i_index),64));
end behav;
