# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.4
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

#
# Settings for Xilinx implementation flow
#
set top_module nfa_accept_samples_generic_hw
set language vhdl
set family spartan3a
set device xc3s200a
set package vq100
set speed -5
set clock ap_clk
set fsm_ext "auto"

# For customizing the implementation flow
set optimization_goal speed    ;# speed|area
set optimization_effort high   ;# normal|high
set register_duplication false ;# true|false
set register_balancing no      ;# yes|no
set par_effort high            ;# std|high|extra
set add_io_buffers false       ;# true/false
