// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern int nfa_accept_samples_generic_hw (const nfa_t* nfa, const uint8_t sample_buffer[5120], const uint32_t sample_buffer_length, const uint16_t sample_length, const index_t indices[1024], const uint16_t i_size,  sample_iterator_t begin,  sample_iterator_t end,  _Bool stop_on_first,  _Bool accept);

