// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _p_bsf32_hw_HH_
#define _p_bsf32_hw_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct p_bsf32_hw : public sc_module {
    // Port declarations 2
    sc_in< sc_lv<32> > bus_r;
    sc_out< sc_lv<5> > ap_return;


    // Module declarations
    p_bsf32_hw(sc_module_name name);
    SC_HAS_PROCESS(p_bsf32_hw);

    ~p_bsf32_hw();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<5> > p_s_phi_fu_139_p62;
    sc_signal< sc_lv<1> > tmp_fu_246_p1;
    sc_signal< sc_lv<1> > tmp_10_fu_250_p3;
    sc_signal< sc_lv<1> > tmp_11_fu_258_p3;
    sc_signal< sc_lv<1> > tmp_12_fu_266_p3;
    sc_signal< sc_lv<1> > tmp_13_fu_274_p3;
    sc_signal< sc_lv<1> > tmp_14_fu_282_p3;
    sc_signal< sc_lv<1> > tmp_15_fu_290_p3;
    sc_signal< sc_lv<1> > tmp_16_fu_298_p3;
    sc_signal< sc_lv<1> > tmp_17_fu_306_p3;
    sc_signal< sc_lv<1> > tmp_18_fu_314_p3;
    sc_signal< sc_lv<1> > tmp_19_fu_322_p3;
    sc_signal< sc_lv<1> > tmp_20_fu_330_p3;
    sc_signal< sc_lv<1> > tmp_21_fu_338_p3;
    sc_signal< sc_lv<1> > tmp_22_fu_346_p3;
    sc_signal< sc_lv<1> > tmp_23_fu_354_p3;
    sc_signal< sc_lv<1> > tmp_24_fu_362_p3;
    sc_signal< sc_lv<1> > tmp_25_fu_370_p3;
    sc_signal< sc_lv<1> > tmp_26_fu_378_p3;
    sc_signal< sc_lv<1> > tmp_27_fu_386_p3;
    sc_signal< sc_lv<1> > tmp_28_fu_394_p3;
    sc_signal< sc_lv<1> > tmp_29_fu_402_p3;
    sc_signal< sc_lv<1> > tmp_30_fu_410_p3;
    sc_signal< sc_lv<1> > tmp_31_fu_418_p3;
    sc_signal< sc_lv<1> > tmp_32_fu_426_p3;
    sc_signal< sc_lv<1> > tmp_33_fu_434_p3;
    sc_signal< sc_lv<1> > tmp_34_fu_442_p3;
    sc_signal< sc_lv<1> > tmp_35_fu_450_p3;
    sc_signal< sc_lv<1> > tmp_36_fu_458_p3;
    sc_signal< sc_lv<1> > tmp_37_fu_466_p3;
    sc_signal< sc_lv<1> > tmp_38_fu_474_p3;
    sc_signal< sc_lv<1> > tmp_39_fu_482_p3;
    sc_signal< sc_lv<5> > merge_phi_fu_237_p4;
    static const sc_lv<5> ap_const_lv5_0;
    static const bool ap_true;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const sc_lv<5> ap_const_lv5_3;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<5> ap_const_lv5_5;
    static const sc_lv<5> ap_const_lv5_6;
    static const sc_lv<5> ap_const_lv5_7;
    static const sc_lv<5> ap_const_lv5_8;
    static const sc_lv<5> ap_const_lv5_9;
    static const sc_lv<5> ap_const_lv5_A;
    static const sc_lv<5> ap_const_lv5_B;
    static const sc_lv<5> ap_const_lv5_C;
    static const sc_lv<5> ap_const_lv5_D;
    static const sc_lv<5> ap_const_lv5_E;
    static const sc_lv<5> ap_const_lv5_F;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_11;
    static const sc_lv<5> ap_const_lv5_12;
    static const sc_lv<5> ap_const_lv5_13;
    static const sc_lv<5> ap_const_lv5_14;
    static const sc_lv<5> ap_const_lv5_15;
    static const sc_lv<5> ap_const_lv5_16;
    static const sc_lv<5> ap_const_lv5_17;
    static const sc_lv<5> ap_const_lv5_18;
    static const sc_lv<5> ap_const_lv5_19;
    static const sc_lv<5> ap_const_lv5_1A;
    static const sc_lv<5> ap_const_lv5_1B;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<5> ap_const_lv5_1E;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_return();
    void thread_merge_phi_fu_237_p4();
    void thread_p_s_phi_fu_139_p62();
    void thread_tmp_10_fu_250_p3();
    void thread_tmp_11_fu_258_p3();
    void thread_tmp_12_fu_266_p3();
    void thread_tmp_13_fu_274_p3();
    void thread_tmp_14_fu_282_p3();
    void thread_tmp_15_fu_290_p3();
    void thread_tmp_16_fu_298_p3();
    void thread_tmp_17_fu_306_p3();
    void thread_tmp_18_fu_314_p3();
    void thread_tmp_19_fu_322_p3();
    void thread_tmp_20_fu_330_p3();
    void thread_tmp_21_fu_338_p3();
    void thread_tmp_22_fu_346_p3();
    void thread_tmp_23_fu_354_p3();
    void thread_tmp_24_fu_362_p3();
    void thread_tmp_25_fu_370_p3();
    void thread_tmp_26_fu_378_p3();
    void thread_tmp_27_fu_386_p3();
    void thread_tmp_28_fu_394_p3();
    void thread_tmp_29_fu_402_p3();
    void thread_tmp_30_fu_410_p3();
    void thread_tmp_31_fu_418_p3();
    void thread_tmp_32_fu_426_p3();
    void thread_tmp_33_fu_434_p3();
    void thread_tmp_34_fu_442_p3();
    void thread_tmp_35_fu_450_p3();
    void thread_tmp_36_fu_458_p3();
    void thread_tmp_37_fu_466_p3();
    void thread_tmp_38_fu_474_p3();
    void thread_tmp_39_fu_482_p3();
    void thread_tmp_fu_246_p1();
};

}

using namespace ap_rtl;

#endif
